const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),
  loadAccounts: () => ipcRenderer.invoke('accounts:load'),
  addAccount: (a) => ipcRenderer.invoke('accounts:add', a),
  removeAccount: (id) => ipcRenderer.invoke('accounts:remove', id),
  updateAccount: (id, data) => ipcRenderer.invoke('accounts:update', id, data),
  reencryptAccounts: (accounts) => ipcRenderer.invoke('accounts:reencrypt', accounts),
  reorderAccounts: (ids) => ipcRenderer.invoke('accounts:reorder', ids),
  openLogin: () => ipcRenderer.invoke('roblox:openLogin'),
  cancelLogin: () => ipcRenderer.send('login:cancel'),
  validateCookie: (cookie) => ipcRenderer.invoke('roblox:validateCookie', cookie),
  launchRoblox: (id, cookie, target) => ipcRenderer.invoke('roblox:launch', id, cookie, target),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  loadSettings: () => ipcRenderer.invoke('settings:load'),
  saveSettings: (data) => ipcRenderer.invoke('settings:save', data),
  multiInstanceStatus: () => ipcRenderer.invoke('multiinstance:status'),
  readGenHistory: () => ipcRenderer.invoke('genhistory:read'),
  writeGenHistory: (list) => ipcRenderer.invoke('genhistory:write', list),
  clearGenHistory: () => ipcRenderer.invoke('genhistory:clear'),
  readFFlags: () => ipcRenderer.invoke('fflag:read'),
  writeFFlags: (flags) => ipcRenderer.invoke('fflag:write', flags),
  onChromeProgress: (cb) => ipcRenderer.on('chrome:download-progress', (_, data) => cb(data)),
  onRobloxClosed: (cb) => ipcRenderer.on('roblox:closed', (_, id) => cb(id)),
  getRobloxVersion: () => ipcRenderer.invoke('roblox:getVersion'),
  getGameName: (placeId, cookie) => ipcRenderer.invoke('roblox:getGameName', placeId, cookie),
});
